spring.application.name=${SPRING_APP_NAME:eazybankbackendreact}
# No spring.security.user.* properties needed here because we define users in-memory in ProjectSecurityConfig.
logging.level.org.springframework.security=TRACE

logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
